### ISSUE TITLE
error on  start lims

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [maxplanck-ie/parkour#37] opened 2018-05-02 13:20 UTC
I have tryied the docker version . However I  try to restar the sever manualy using run.sh
I have this error:
```
May 02, 2018 - 14:53:51
Django version 1.11.12, using settings 'wui.settings.prod'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
root@00213359f166:/usr/src/app# l
README.md	    index_generator	   manage.py  requirements  usage
common		    invoicing		   media      run.sh	    wui
docs		    library		   notebooks  sample
fabfile.py	    library_preparation    pooling    static
flowcell	    library_sample_shared  report     staticfiles
incoming_libraries  logs		   request    stats
root@00213359f166:/usr/src/app# exit
exit

[maurizio@localhost docker-parkour]$ docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                       PORTS                              NAMES
58e95147e34b        dockerparkour_parkour-web:latest   "python manage.py cre"   5 days ago          Up 5 days                    8000/tcp                           dockerparkour_parkour-web_run_5
d7a13deb03c1        dockerparkour_parkour-web:latest   "python manage.py mig"   5 days ago          Restarting (0) 4 hours ago   8000/tcp                           dockerparkour_parkour-web_run_4
732215b8675b        dockerparkour_parkour-web:latest   "python manage.py cre"   12 days ago         Up 5 days                    8000/tcp                           dockerparkour_parkour-web_run_3
d97a4e197789        dockerparkour_parkour-web:latest   "python manage.py cre"   12 days ago         Up 12 days                   8000/tcp                           dockerparkour_parkour-web_run_2
7ef9a01b15c1        dockerparkour_parkour-web:latest   "python manage.py mig"   12 days ago         Restarting (0) 2 days ago    8000/tcp                           dockerparkour_parkour-web_run_1
00213359f166        dockerparkour_parkour-web:latest   "/usr/local/bin/gunic"   12 days ago         Up 12 days                   8000/tcp, 0.0.0.0:8888->8888/tcp   parkour-web
ce76bc93ac40        postgres:9.5                       "docker-entrypoint.sh"   12 days ago         Up 12 days                   0.0.0.0:5433->5432/tcp             parkour-postgres


```s
How can change the  server http and how can run localy ?

**Comment by dpryan79** [comment] 2018-05-02 13:31
There is no reason to restart things with `run.sh`, use the normal `docker-compose restart ...` command. `run.sh`is likely failing because there are so many excess containers running. I suggest killing everything except `postgres` and redo `docker-compose up`.

**Comment by bioinfo-dirty-jobs** [comment] 2018-05-02 13:57
```
[maurizio@localhost docker-parkour]$ docker-compose up
parkour-postgres is up-to-date
Recreating parkour-web ... done
Recreating parkour-nginx ... error

ERROR: for parkour-nginx  Cannot start service parkour-nginx: driver failed programming external connectivity on endpoint parkour-nginx (89de19e9007055de9a54492797f0fe0dd8846f09729081821275a7246af74c89): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for parkour-nginx  Cannot start service parkour-nginx: driver failed programming external connectivity on endpoint parkour-nginx (89de19e9007055de9a54492797f0fe0dd8846f09729081821275a7246af74c89): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by dpryan79** [comment] 2018-05-02 14:09
You have something on port 80 already, so either change that or change the docker compose yaml to redirect a different external port to port 80 in the container (the line you want [is here](https://github.com/maxplanck-ie/docker-parkour/blob/master/docker-compose.yml#L28)).

**Comment by bioinfo-dirty-jobs** [comment] 2018-05-04 13:02
I have try to restar I have some toher problems

```
docker-compose  up
Removing parkour-nginx
Starting parkour-postgres ... done
Starting parkour-web      ... done
Starting b8b06e2a387e_parkour-nginx ... done
Attaching to parkour-postgres, parkour-web, b8b06e2a387e_parkour-nginx
parkour-postgres    | LOG:  database system was interrupted; last known up at 2018-05-04 12:30:52 UTC
parkour-web         | [2018-05-04 12:33:25 +0000] [1] [INFO] Starting gunicorn 19.7.1
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
parkour-web         | [2018-05-04 12:33:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
parkour-web         | [2018-05-04 12:33:25 +0000] [1] [INFO] Using worker: sync
parkour-web         | [2018-05-04 12:33:25 +0000] [9] [INFO] Booting worker with pid: 9
parkour-web         | [2018-05-04 12:33:25 +0000] [11] [INFO] Booting worker with pid: 11
parkour-postgres    | LOG:  database system was not properly shut down; automatic recovery in progress
parkour-postgres    | LOG:  invalid record length at 0/1900A00
parkour-postgres    | LOG:  redo is not required
b8b06e2a387e_parkour-nginx exited with code 1
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
parkour-postgres    | LOG:  MultiXact member wraparound protections are now enabled
parkour-postgres    | LOG:  database system is ready to accept connections
parkour-postgres    | LOG:  autovacuum launcher started
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
b8b06e2a387e_parkour-nginx | nginx: [emerg] PEM_read_bio_X509_AUX("/etc/parkour.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)

```

**Comment by dpryan79** [comment] 2018-06-25 08:18
I'll close this since I can't reproduce it.

**Closed by dpryan79** 2018-06-25 08:18 UTC
